### ISSUE TITLE
Crear esqueleto de la aplicación NodeJS

### ISSUE THREAD

**Issue by omiras** [FOAP-NETMIND-PROMOCIO-2020/friendlyrent#1]
### Objetivo
Crear el esqueleto de nuestra aplicación NodeJS

### Análisis y diseño

1. Inicializar un paquete NPM
2. Instalar [Express](https://www.npmjs.com/package/express), [Nodemon](https://www.npmjs.com/package/nodemon)
3. Configurar package.json para poder iniciar la aplicación con "npm start"
4. Crear un endpoint a '/'  y que retorne una respuesta simple. Algo así como "Funciona!"
5. Levantar un servidor NodeJS en el puerto 3000.
6. Subir el proyecto a GitHub. Tener en cuenta que carpetas hay que subir y cuáles no. (ejemplo: node_modules)

### ¿Cómo probarlo?
Todos los integrantes del proyecto deberían poder hacer un pull request del repositorio con el esqueleto del proyecto. 

`git clone FOAP-NETMIND-PROMOCIO-2020/friendlyrent`
`npm install`
`npm start`

**Comment by huiterjrv** [comment]
hola

**Comment by aplidinio** [comment]
Como tamoh?

**Comment by kira14** [comment]
parece completito

**Comment by huiterjrv** [comment]
![que cosas](https://i.pinimg.com/originals/0d/b5/c7/0db5c7603457218efa4b24840ffdc861.gif)
