### ISSUE TITLE
Lista de apartamentos - Home Page

### ISSUE THREAD

**Issue by omiras** [FOAP-NETMIND-PROMOCIO-2020/friendlyrent#18]
### Objetivo
Adaptar la plantilla "lista de apartamentos" a los datos esperados de la BBDD

### Ánalisis y diseño

- Decidir que subconjunto de campos de la BBDD van a aparecer en la vista. Cometarlo con @SergiHub @sagalto68 
- Crear un endpoint que devuelve la lista de apartamentos. Por ejemplo "/"
- SI el usuario que ha iniciado sesión es "inquilino", (o no, o simplemente no está identificado); puede ver la lista de apartamentos. Mientras no esté implementada la autentificación, emularlo pasándole un parámetro a la vista, por ejemplo, "role"
  - Debe aparecer para cada apartamento un botón que diga "Alquilar". De momento el botón  no hará nada
- Si el usuario es tipo **propietario**, debemos mostrar la lista de **sus apartamentos en propiedad**. 
Dado que esto es tarea del controlador, por el momento, un propietario verá lo mismo que un **inquilino**

**Comment by lauraDrums** [comment]
1. Añadid el condicional para que muestre para todos los apartamentos que actualmente aparecen de manera estática, de modo que si le pasamos la variable "role=inquilino", entonces se vea el botón de alquilar. En caso contrario, no.
2. Aunque sean datos dummies; cambiadlos un poquito por lo que esperáis que venga de una base de datos de pisos de España. Incluso os podeis fijar en algun registro que ya tengo creado en la BBDD en la colección 'Apartments'

**Comment by rawl0408** [comment]
Hola Team!
Hemos modificado Home Page -> Lista de Apartamentos (con sus características).
Para poder acceder y comprobar su correcto funcionamiento tenéis que dirigiros a la siguiente dirección:
- http://localhost:3000/

Test a realizar:
- Comprobar que aparecen los apartamentos listados
- Comprobar que las características de los apartamentos están presentes
- Comprobar que el role "inquilino" hace que podamos ver el botón de "Alquiler" dentro de la imagen principal del apartamento (podéis modificar el archivo " controllers \ apartmentControllers.js " y cambiar el valor "inquilino" por otro diferente, así el botón de "Alquiler" no aparecerá en la imágen. 

@omiras

**Comment by hmirodski** [comment]
La etiqueta alquilar funciona, pero tal vez debería estar escrito en inglés.
