### ISSUE TITLE
Probar la API de Idealista

### ISSUE THREAD

**Issue by omiras** [FOAP-NETMIND-PROMOCIO-2020/friendlyrent#7]
## Objetivo
Probar la API de Idealista

## Análisis y diseño
Aprender como utilizar la API de Idealista y generar algunas consultas para recuperar datos.

Ejemplo de llamada:
`curl -X POST -H "Authorization: Bearer {{OAUTH_BEARER}}" -H "Content-Type: multipart/form-data;" -F "center=40.430,-3.702" -F "propertyType=homes" -F "distance=15000" -F "operation=sale" "https://api.idealista.com/3.5/es/search"`

## ¿Cómo probarlo?
Crear una página de la Wiki explicando como usar la API de Idealista mediante un par de ejemplos. Los pantallazos son bienvenidos.

[oauth2-documentation.pdf](https://github.com/FOAP-NETMIND-PROMOCIO-2020/friendlyrent/files/4914311/oauth2-documentation.pdf)

[Uploading property-search-api-v3_5.pdf…]()

**Comment by omiras** [comment]
Sería interesante en el futuro ver como consumir la API desde NodeJS
https://www.youtube.com/watch?v=ZtLVbJk7KcM

**Comment by omiras** [comment]
@huiterjrv @LarryMerino @jorditarga Añadid un comentario o varios comentarios con la siguiente info:
1. Como hacer la llamada a la API (podéis emborronar la contraseña). 
2. Resultado JSON (pantallazo)
3. Que campos del JSON son interesantes para nuestra aplicación

**Comment by omiras** [comment]
Tenéis los pasos de como probar la funcionalidad en https://github.com/FOAP-NETMIND-PROMOCIO-2020/friendlyrent/wiki/Como-probar-la-api-de-idealista

**Comment by huiterjrv** [comment]
# Observación 

Falta destacar que no se pudo lograr hacer una llamada HTTP en NodeJs con los parámetros que se deben pasarle 
>El [documento](https://drive.google.com/file/d/1vzU8TdyePpq3mSVY4PGSNF9Cl4mvP_mn/view) que muestra los parámetros que se pasan lo tiene el manager @omiras 

### Documentación de manera para lograr en HTTP  

En las documentaciones que le estaré presentando aparecen npm que se probaron para poder ejecutarlo desde un script como también las llamadas AJAX  

- [nodejs](https://nodejs.org/api/http.html)
- [cURL](https://flaviocopes.com/http-curl/)
-  [llamadas HTTP](https://attacomsian.com/blog/node-http-post-request#)
- [npm curl](https://www.npmjs.com/package/curl)
- [npm request](https://www.npmjs.com/package/request)

>recordar es una llamadas POST  y por favor si ven algo indicar o comunicarse con el equipo @LarryMerino @jorditarga @huiterjrv
