### ISSUE TITLE
Hacer un esquema del modelo de datos de la aplicación

### ISSUE THREAD

**Issue by omiras** [FOAP-NETMIND-PROMOCIO-2020/friendlyrent#74]
1. Crear un esquema del modelo de datos de la aplicación con una herramienta tipo [esta](https://dbdiagram.io/home).
2. Comentar algunas funciones del modelo de datos (getAllAvailableApartmentsForBooking, por ejemplo)
3. Poner toda esta información en una página de la Wiki
4. Pros y contras de este modelo de datos, dificultades con las que os habéis encontrado, etc.

**Comment by kira14** [comment]
La solución comentada (dbdiagram.io) funciona con BBDD basadas en SQL. 
Implementamos el esquema con la apliacación dbSchema que es similar y funciona con BBDD basadas en node.js y mongoDB.
